//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoanWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailOrder
    {
        public int idProduct { get; set; }
        public int idOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Product Product { get; set; }
    }
}
