//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoanWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_info()
        {
            this.Accounts = new HashSet<Account>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int idUser { get; set; }
        public string nameUser { get; set; }
        public Nullable<System.DateTime> birthUser { get; set; }
        public string sexUser { get; set; }
        public string phoneNumberUser { get; set; }
        public string emailUser { get; set; }
        public string addressUser { get; set; }
        public Nullable<int> roleAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual RoleAccount RoleAccount1 { get; set; }
    }
}
